### ISSUE TITLE
Get-LMEscalationChain destination export

### ISSUE THREAD

**Issue by jessewolcott** [stevevillardi/Logic.Monitor#11]
Hello, great module! I'm trying to extract destination addresses out of Get-LMEscalationChain, and I believe its returning a malformed object. I have 3 emails in my escalation chain, and its returning {@{type=single; period=; stages=System.Object[]}}, which I think is an extra set of braces!

I might be wrong

**Comment by stevevillardi** [comment]
Thanks for the report, let me take a look at the issue and see if I can reproduce it.

**Comment by jessewolcott** [comment]
Sure thing, let me know if I can help

**Comment by stevevillardi** [comment]
So I took a look at the output from one of my portals and the code seems to be correct, I think because of the way PowerShell displays nested array objects with multiple fields you end up just seeing the object type within the array instead of the entire output. If you were to actually try to retrieve the value you can access the data just fine.

![image](https://user-images.githubusercontent.com/42367049/232259797-fca324f9-e6ad-4afc-8cc3-71eda08bf796.png)

Or if you convert it to JSON as well you can see the entire result set:

![image](https://user-images.githubusercontent.com/42367049/232259841-bb0f6ecd-cbd3-45d3-bfef-cbcb213d3ccb.png)

Let me know if that answers your issue, otherwise happy to discuss this further to better understand what you are looking for.

**Comment by jessewolcott** [comment]
Nope, that is perfect, turns out I didn't go deep enough. Thank you for the explanation, its working great!
